# The Notebook Will Process the Raw Medicare Files
We need two Medicare Part B payment files to do the simulation of the proposed Medicare Physician Fee Schedule. The first two variables are the locations of the files on the Web. Download and unzip both files. When the notebook as been run, there will be two files named with the other two variables. The next script will need those file names, so if you change them, you will need to change them in the other script(s).

In [1]:
medicareFileUrl = "http://www.cms.gov/apps/ama/license.asp?file=https://downloads.cms.gov/files/Medicare-Physician-and-Other-Supplier-PUF.zip"
medicareAggFileUrl = "https://downloads.cms.gov/files/Medicare-Physician-and-Other-Supplier-NPI-Aggregate_CY2016.zip"

medicare_saved = "medicare_saved.pkl"
medicare_agg_saved = "medicare_agg_saved.pkl"

After you have downloaded and unzip the files. You will need to tell this notebook where those files are located. Replace the current locations with the locations of the files on your computer. If you put them in the same folder, you will not need to put the full path to the files.

In [2]:
medicareFileName = "/Users/swaldren/OG/ProviderData/PartB/Medicare_Provider_Util_Payment_PUF_CY2016.txt"
medicareAggFileName = "/Users/swaldren/OG/ProviderData/PartB/Medicare_Physician_and_Other_Supplier_NPI_Aggregate_CY2016.txt"

In [3]:
import pandas as pd

In [4]:
df_medicare = pd.read_csv(medicareFileName, sep='\t', header=0, skiprows=[1])
df_medicare.set_index('NPI')
df_medicare.head()

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,NPI,NPPES_PROVIDER_LAST_ORG_NAME,NPPES_PROVIDER_FIRST_NAME,NPPES_PROVIDER_MI,NPPES_CREDENTIALS,NPPES_PROVIDER_GENDER,NPPES_ENTITY_CODE,NPPES_PROVIDER_STREET1,NPPES_PROVIDER_STREET2,NPPES_PROVIDER_CITY,...,HCPCS_CODE,HCPCS_DESCRIPTION,HCPCS_DRUG_INDICATOR,LINE_SRVC_CNT,BENE_UNIQUE_CNT,BENE_DAY_SRVC_CNT,AVERAGE_MEDICARE_ALLOWED_AMT,AVERAGE_SUBMITTED_CHRG_AMT,AVERAGE_MEDICARE_PAYMENT_AMT,AVERAGE_MEDICARE_STANDARD_AMT
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99217,Hospital observation care discharge,N,57.0,55,57,72.743158,325.157895,54.474386,55.807193
1,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99219,Hospital observation care typically 50 minutes,N,38.0,38,38,135.010000,614.000000,105.850000,107.230000
2,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99220,Hospital observation care typically 70 minutes...,N,23.0,23,23,189.239565,769.347826,146.116522,144.278696
3,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99221,"Initial hospital inpatient care, typically 30 ...",N,20.0,20,20,100.750000,460.000000,78.990000,80.280000
4,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99222,"Initial hospital inpatient care, typically 50 ...",N,96.0,87,96,136.250000,625.000000,105.477604,107.007708

Since the Medicare files are large, the following filters out only the columns we care about.

In [6]:
df_medicare_filter = df_medicare[['NPI', 'PLACE_OF_SERVICE', 'HCPCS_CODE', 'LINE_SRVC_CNT', 'PROVIDER_TYPE']]
df_medicare_filter.to_pickle(medicare_saved)

In [7]:
df_medicare_agg = pd.read_csv(medicareAggFileName, sep='\t')
df_medicare_agg.set_index('NPI')
df_medicare_agg.head()

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,NPI,NPPES_PROVIDER_LAST_ORG_NAME,NPPES_PROVIDER_FIRST_NAME,NPPES_PROVIDER_MI,NPPES_CREDENTIALS,NPPES_PROVIDER_GENDER,NPPES_ENTITY_CODE,NPPES_PROVIDER_STREET1,NPPES_PROVIDER_STREET2,NPPES_PROVIDER_CITY,...,BENEFICIARY_CC_DEPR_PERCENT,BENEFICIARY_CC_DIAB_PERCENT,BENEFICIARY_CC_HYPERL_PERCENT,BENEFICIARY_CC_HYPERT_PERCENT,BENEFICIARY_CC_IHD_PERCENT,BENEFICIARY_CC_OST_PERCENT,BENEFICIARY_CC_RAOA_PERCENT,BENEFICIARY_CC_SCHIOT_PERCENT,BENEFICIARY_CC_STRK_PERCENT,BENEFICIARY_AVERAGE_RISK_SCORE
0,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,42.0,53.0,67.0,75.0,53.0,12.0,49.0,9.0,13.0,2.0239
1,1003000134,CIBULL,THOMAS,L,M.D.,M,I,2650 RIDGE AVE,EVANSTON HOSPITAL,EVANSTON,...,13.0,21.0,46.0,54.0,26.0,9.0,38.0,1.0,3.0,1.0925
2,1003000142,KHALIL,RASHID,NaN,M.D.,M,I,4126 N HOLLAND SYLVANIA RD,SUITE 220,TOLEDO,...,50.0,37.0,53.0,73.0,37.0,8.0,75.0,6.0,5.0,1.5809
3,1003000407,GIRARDI,DAVID,J,D.O.,M,I,100 HOSPITAL RD,NaN,BROOKVILLE,...,47.0,40.0,69.0,75.0,64.0,15.0,43.0,12.0,14.0,2.0000
4,1003000423,VELOTTA,JENNIFER,A,M.D.,F,I,11100 EUCLID AVE,NaN,CLEVELAND,...,28.0,27.0,41.0,52.0,21.0,NaN,46.0,NaN,0.0,0.9540

Since the Medicare files are large, the following filters out only the columns we care about.

In [9]:
df_medicare_agg_filter = df_medicare_agg[['NPI', 'NPPES_ENTITY_CODE', 'BENEFICIARY_AVERAGE_RISK_SCORE', 'NPPES_PROVIDER_STATE',
                                  'TOTAL_UNIQUE_BENES', 'PROVIDER_TYPE']]
df_medicare_agg_filter.to_pickle(medicare_agg_saved)

## Next Step
You can now open the "Calculate Model" Notebook and run it.